#pragma once

#define PACKET_BASE_SPACE_OCCUPIED 8
#define NET_BUFFER_SIZE_TOTAL 512
#define NET_PACKET_COMPONENT_DATA_SIZE_TOTAL (NET_BUFFER_SIZE_TOTAL - PACKET_BASE_SPACE_OCCUPIED)

#define DEFAULT_PACKET_COMPONENT_SIZE 6

#define FIXED_UPDATES_PER_SECOND 60.f
#define FIXED_UPDATE_DELTA_TIME (1.f / FIXED_UPDATES_PER_SECOND)
#define UPDATE_ITERATOR_RESET_NUMBER ((int)(FIXED_UPDATES_PER_SECOND) * 512)

#define DEFAULT_SERVER_ADDRESS_WIDE TEXT("127.0.0.1")
#define DEFAULT_SERVER_ADDRESS "127.0.0.1"
#define DEFAULT_SERVER_PORT (u_short)42000

#define SIO_UDP_CONNRESET _WSAIOW(IOC_VENDOR, 12)

#define NET_INACTIVE_CHECKS_PER_UPDATE_PERCENT (1.f / 20.f)

#define NET_TIME_UNTIL_TIME_OUT_SEC 2.5f

#define NET_TIME_UNTIL_NEXT_SERVER_PING 0.2f

#define MEMBER_VARIABLE_STORAGE_DEFAULT_SIZE 2
#define VARIABLE_DATA_OBJECT_DEFAULT_SIZE 4

#define MAX_MEMBER_VARIABLE_OFFSET 1024
#define MAX_MEMBER_VARIABLE_SIZE 64

#define MEMBER_VARIABLE_OFFSET_BITS 10
#define MEMBER_VARIABLE_SIZE_BITS 6

#define CONNECTION_COMPONENT_SIZE_EMPTY (DEFAULT_PACKET_COMPONENT_SIZE + 2)
#define CONNECTION_COMPONENT_DATA_SIZE (NET_PACKET_COMPONENT_DATA_SIZE_TOTAL - CONNECTION_COMPONENT_SIZE_EMPTY)

#define REPLICATION_COMPONENT_SIZE_EMPTY (DEFAULT_PACKET_COMPONENT_SIZE + 4)
#define REPLICATION_DATA_SIZE (NET_PACKET_COMPONENT_DATA_SIZE_TOTAL - REPLICATION_COMPONENT_SIZE_EMPTY)