#pragma once

#define PACKET_BASE_SPACE_OCCUPIED 8
#define NET_BUFFER_SIZE_TOTAL 512
#define NET_PACKET_COMPONENT_DATA_SIZE_TOTAL (NET_BUFFER_SIZE_TOTAL - PACKET_BASE_SPACE_OCCUPIED)

#define DEFAULT_PACKET_COMPONENT_SIZE 6

#define FIXED_UPDATES_PER_SECOND 60.f
#define FIXED_UPDATE_DELTA_TIME (1.f / FIXED_UPDATES_PER_SECOND)
#define UPDATE_ITERATOR_RESET_NUMBER ((int)(FIXED_UPDATES_PER_SECOND) * 512)

#define DEFAULT_SERVER_ADDRESS TEXT("127.0.0.1")
#define DEFAULT_SERVER_PORT (u_short)42000

#define SIO_UDP_CONNRESET _WSAIOW(IOC_VENDOR, 12)

#define NET_INACTIVE_CHECKS_PER_UPDATE_PERCENT (1.f / 20.f)

#define NET_TIME_UNTIL_TIME_OUT_SEC 2.f

#define NET_TIME_UNTIL_NEXT_SERVER_PING 0.2f