#pragma once

#define PACKET_BASE_SPACE_OCCUPIED 6
#define PACKET_TOTAL_SIZE 512
#define PACKET_COMPONENT_TOTAL_SPACE PACKET_TOTAL_SIZE - PACKET_BASE_SPACE_OCCUPIED

#define DEFAULT_PACKET_COMPONENT_SIZE 4
